AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Resources for Precise Ledger Pro Demo.

Resources:
  # IAM Role for App Runner Service Instances
  AppRunnerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apprunner.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppRunnerServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                Resource: arn:aws:logs:*:*

  # IAM Policy for App Runner Service Instances
  AppRunnerServiceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: app-runner-service-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:CreateLogGroup
            Resource: arn:aws:logs:*:*:log-group:*
      Roles:
        - !Ref AppRunnerServiceRole

  # IAM Role for App Runner to access ECR
  AppRunnerECRRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apprunner.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECRAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                Resource: "*"

Outputs:
  AppRunnerServiceRoleArn:
    Value: !GetAtt AppRunnerServiceRole.Arn
    Export:
      Name: AppRunnerServiceRoleArn

  AppRunnerECRRoleArn:
    Value: !GetAtt AppRunnerECRRole.Arn
    Export:
      Name: AppRunnerECRRoleArn
