# System Config - Common
quarkus.datasource.jdbc.url=jdbc:h2:mem:default
quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
# System Config - Prod
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://34.131.89.55:5432/postgres
%prod.quarkus.datasource.username=postgres
%prod.quarkus.datasource.password=postgres
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.hibernate-orm.database.generation=none